name: Deploy to Linux Server

on:
  push:
    branches:
      - main # Modify this to match your repository's default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH agent
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.HOST_SERVER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd ./coding/spots
            chmod +x deploy.sh
            ./deploy.sh
